#!/usr/bin/env bash

## Install ansible
sudo apt-add-repository -y ppa:ansible/ansible
sudo apt-get update -y
sudo apt-get install -y curl git software-propeties-common ansible

## pull ansible
sudo ansible-pull -U https://github.com/ppulfer17/ansible.git